#!/bin/bash
# Created by the VLSCI job script generator
# Fri Jun 14 2013 10:12:38 GMT+1000 (EST)

# Queue for the job:
#PBS -q batch

# The name of the job:
#PBS -N srst2

# The total amount of memory in gigabytes used by the whole job:
#PBS -l mem=4gb

# Send yourself an email when the job (a)borts abnormally (b)egins (e)nds successfully
#PBS -m abe

# The maximum running time of the job in hours:mins:secs
#PBS -l walltime=0:10:00
# Run the job from the directory where it was launched:
cd $PBS_O_WORKDIR

# The modules to load:
module load bowtie-gcc/2-2.1.0
module load samtools-gcc/0.1.19

# The job command(s):
./srst2.py --input_pe data/pool11_tag1_1.fastq.gz data/pool11_tag1_2.fastq.gz --output pool11_tag1 --build data/ADK.fasta data/FUMC.fasta data/GYRB.fasta data/ICD.fasta data/MDH.fasta data/PURA.fasta data/RECA.fasta  --log log --input_type q
