#!/bin/bash
# Created by the VLSCI job script generator
# Fri Jun 14 2013 10:12:38 GMT+1000 (EST)

# Queue for the job:
#PBS -q batch

# The name of the job:
#PBS -N srst2

# The total amount of memory in gigabytes used by the whole job:
#PBS -l mem=4gb

# Send yourself an email when the job (a)borts abnormally (b)egins (e)nds successfully
#PBS -m abe

# The maximum running time of the job in hours:mins:secs
#PBS -l walltime=0:20:00
# Run the job from the directory where it was launched:
cd $PBS_O_WORKDIR

# The modules to load:
module load bowtie-gcc/2-2.1.0
module load samtools-gcc/0.1.19
module load perl/5.10.1

# The job command(s):
./srst2.pl -pe -t -q -b /vlsci/VR0082/hdashnow/blaCTX-M.fsa -i 6581_3_8_1.fastq.gz,6581_3_8_2.fastq.gz -o 6581_3_8

