#!/bin/bash
# Created by the VLSCI job script generator
# Fri Jun 14 2013 10:12:38 GMT+1000 (EST)

# Queue for the job:
#PBS -q batch

# The name of the job:
#PBS -N srst2

# The total amount of memory in gigabytes used by the whole job:
#PBS -l mem=4gb

# Send yourself an email when the job (a)borts abnormally (b)egins (e)nds successfully
#PBS -m abe

# The maximum running time of the job in hours:mins:secs
#PBS -l walltime=0:40:00
# Run the job from the directory where it was launched:
cd $PBS_O_WORKDIR

# The modules to load:
module load bowtie-gcc/2-2.1.0
module load samtools-gcc/0.1.19
module load python-gcc/2.7.3

# The job command(s):
./srst2.py --input_pe  /vlsci/VR0082/hdashnow/raw_data/Shigella_validation_set/6581_3#8_1.fastq.gz /vlsci/VR0082/hdashnow/raw_data/Shigella_validation_set/6581_3#8_2.fastq.gz  --output 6581_3#8 --build /vlsci/VR0082/hdashnow/blaCTX-M.fsa --log 6581_3#8.log --input_type q
